name: RSpec

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Maintained versions: 2.7, 3.0, 3.1
        # Security updates only: 2.6 (EOL: 2022-03-31)
        # Source: https://www.ruby-lang.org/en/downloads/branches/
        ruby: [ 2.6, 2.7, 3.0, 3.1 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the tests
        run: bundle exec rspec
